### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by srwgin** [Frizz925/gbf-autopilot#1] opened 2017-06-17 06:38 UTC
I delete everything then make a clear install

npm WARN deprecated guid@0.0.12: Please use node-uuid instead. It is much better.
npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
npm WARN deprecated babel-root-import@3.2.2: plugin was unnamed to 'babel-plugin-root-import', please use the new package
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN eslint-plugin-import@2.3.0 requires a peer of eslint@2.x - 3.x but none was installed.

**Comment by srwgin** [comment] 2017-06-17 06:39
after I load extension and start
it suck at #quest/extra/event

**Comment by srwgin** [comment] 2017-06-17 06:41
D:\game\gbf\gbf-autopilot>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-plugin-import@2.3.0 requires a peer of eslint@2.x - 3.x but none was installed.

D:\game\gbf\gbf-autopilot>

**Comment by srwgin** [comment] 2017-06-17 06:43
then build

D:\game\gbf\gbf-autopilot>npm run build

> @ build D:\game\gbf\gbf-autopilot
> gulp build

[14:42:42] Using gulpfile D:\game\gbf\gbf-autopilot\gulpfile.js
[14:42:42] Starting 'build:server'...
[14:42:42] Starting 'build:extension'...
[14:42:43] Finished 'build:server' after 1.22 s
[14:42:45] [webpack] Hash: 0fa05bfed0a9073cfbd0
Version: webpack 2.6.1
Time: 2273ms
               Asset     Size  Chunks             Chunk Names
    contentscript.js  57.8 kB       0  [emitted]  contentscript
       background.js   153 kB       1  [emitted]  background
            popup.js  3.16 kB       2  [emitted]  popup
contentscript.js.map    73 kB       0  [emitted]  contentscript
   background.js.map   194 kB       1  [emitted]  background
        popup.js.map  3.28 kB       2  [emitted]  popup
chunk    {0} contentscript.js, contentscript.js.map (contentscript) 49.6 kB [entry] [rendered]
    [0] (webpack)/buildin/global.js 509 bytes {0} {1} [built]
    [8] ./src/lib/messaging/packer.js 361 bytes {0} [built]
   [13] ./~/lodash/isArrayLike.js 830 bytes {0} [built]
   [24] ./~/lodash/_assignValue.js 899 bytes {0} [built]
   [29] ./~/lodash/_isPrototype.js 480 bytes {0} [built]
   [30] ./~/lodash/assign.js 1.57 kB {0} [built]
   [31] ./~/lodash/eq.js 799 bytes {0} [built]
   [43] ./src/contentscript/actions/index.js 1.43 kB {0} [built]
   [48] ./src/contentscript.js 939 bytes {0} [built]
   [49] ./src/contentscript/actions/element.js 1.88 kB {0} [built]
   [50] ./src/contentscript/actions/location.js 556 bytes {0} [built]
   [75] ./~/lodash/_copyObject.js 1.04 kB {0} [built]
   [77] ./~/lodash/_createAssigner.js 1.04 kB {0} [built]
   [96] ./~/lodash/keys.js 884 bytes {0} [built]
  [101] ./~/shortid/index.js 55 bytes {0} [built]
     + 52 hidden modules
chunk    {1} background.js, background.js.map (background) 144 kB [entry] [rendered]
    [1] ./~/debug/src/browser.js 4.73 kB {1} [built]
    [2] ./~/component-emitter/index.js 3.18 kB {1} [built]
   [16] ./~/socket.io-parser/index.js 7.72 kB {1} [built]
   [17] ./~/component-bind/index.js 474 bytes {1} [built]
   [20] ./~/has-binary2/index.js 1.46 kB {1} [built]
   [21] ./~/indexof/index.js 199 bytes {1} [built]
   [37] ./~/socket.io-client/lib/manager.js 12.5 kB {1} [built]
   [39] ./~/socket.io-client/lib/socket.js 7.73 kB {1} [built]
   [42] ./src/background/liveReload.js 370 bytes {1} [built]
   [44] ./~/socket.io-client/lib/index.js 1.74 kB {1} [built]
   [47] ./src/background.js 2.02 kB {1} [built]
   [52] ./~/backo2/index.js 1.4 kB {1} [built]
   [55] ./~/debug/src/debug.js 4.39 kB {1} [built]
   [56] ./~/engine.io-client/index.js 42 bytes {1} [built]
  [109] ./~/socket.io-client/lib/url.js 1.61 kB {1} [built]
     + 32 hidden modules
chunk    {2} popup.js, popup.js.map (popup) 467 bytes [entry] [rendered]
   [51] ./src/popup.js 467 bytes {2} [built]
[14:42:45] Finished 'build:extension' after 2.45 s
[14:42:45] Starting 'build'...
[14:42:45] Finished 'build' after 30 μs

D:\game\gbf\gbf-autopilot>

**Comment by srwgin** [comment] 2017-06-17 06:43
then start

D:\game\gbf\gbf-autopilot>npm start

> @ start D:\game\gbf\gbf-autopilot
> concurrently "node server/server.js" "python controller/controller.py"

[1] Traceback (most recent call last):
[1]   File "controller/controller.py", line 2, in <module>
[1]     from flask import Flask, request
[1] ImportError: No module named flask
[1] python controller/controller.py exited with code 1
[0] Started listening on localhost:49544

**Comment by srwgin** [comment] 2017-06-17 06:44
after load extension then start
it suck at #quest/extra/event

[0] Client '59QqgzvIBDiyUf6OAAAA' connected!
[0] { check: [Function: bound check],
[0]   wait: [Function: bound wait],
[0]   switch: [Function: bound _switch],
[0]   merge: [Function: bound merge],
[0]   click: [Function: bound click],
[0]   support: [Function: bound support],
[0]   'battle.skill': [Function: bound battleSkill],
[0]   'battle.attack': [Function: bound battleAttack],
[0]   'battle.ca': [Function: bound battleCa],
[0]   'battle.summon': [Function: bound battleSummon] }
[0] 59Qqg: 'ByZ3yUfQW' location.change(#quest/extra/event) (60000ms)
[0] 59Qqg: 'BJlb3yLGm-' element(.btn-stage-detail) (60000ms)

**Comment by srwgin** [comment] 2017-06-17 06:57
pip install flask
pip install flask-cors --upgrade

**Comment by srwgin** [comment] 2017-06-17 07:08
finally it done

> @ start D:\game\gbf\gbf-autopilot
> concurrently "node server/server.js" "python controller/controller.py"

[0] Started listening on localhost:49544
[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)

**Comment by srwgin** [comment] 2017-06-18 03:18
after build then run it
it suck at #quest/extra/event

D:\temp\gbf-autopilot>npm start

> @ start D:\temp\gbf-autopilot
> concurrently "node server/server.js" "python controller/controller.py"

[0] Started listening on localhost:49544
[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] Client 'jcnampx4nimycWveAAAA' connected!
[1] 127.0.0.1 - - [18/Jun/2017 11:16:54] "POST /start HTTP/1.1" 200 -
[0] Action: location.change('#quest/extra/event')
[0] Socket: location.change("#quest/extra/event")
[0] Action: wait('.btn-stage-detail')
[0] Socket: element({"selector":".btn-stage-detail","retry":true})
                                                      [0] Error: Action 'B11hluQQZ' element([object Object]) timed out!
[0]     at Timeout._onTimeout (D:\temp\gbf-autopilot\server\dist\server.js:185:22)
[0]     at ontimeout (timers.js:386:14)
[0]     at tryOnTimeout (timers.js:250:5)
[0]     at Timer.listOnTimeout (timers.js:214:5)

**Comment by srwgin** [comment] 2017-06-19 03:21
try to change language also timeout

**Comment by Frizz925** [comment] 2017-06-19 20:14
Try pulling again and report back. It's still in heavy development and many things will break.

**Comment by srwgin** [comment] 2017-06-20 03:34
also time out now
I will try it after you next update

**Comment by Frizz925** [comment] 2017-06-20 11:34
Works just fine here. Also the scenario you're running is just an example, don't expect it to work at the first place.

**Comment by srwgin** [comment] 2017-06-21 04:31
I start bot on #mypage
it success go to #quest/extra event part
but sucked on choose stage


I check the elements it is there
<div class="btn-stage-detail" data-key="6015_2" data-id="6015" data-group="2" data-title="ぴにゃこら狂騒曲"></div>
I do not know why it time out
[gbf-autopilot.zip](https://github.com/Frizz925/gbf-autopilot/files/1090337/gbf-autopilot.zip)
this is my build
can you help me check is build problem
thank you

**Comment by Frizz925** [comment] 2017-06-21 21:59
Inspect both of the background page of the extension and the game page, see if it prints out anything out of ordinary. Also, make sure you've reloaded the extension after building it.

**Comment by srwgin** [comment] 2017-06-22 02:26
WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
it looks like is websocket problem

**Comment by Frizz925** [comment] 2017-06-22 03:52
> and do you test it on mac or windows?

Windows only. [The documentation said so](../#getting-started).

>The control server is tightly coupled with your operating system. Currently it only works on Windows NT using pywin32.

This isn't going anywhere since it's most likely caused by your own browser/game. Closing this since the problem can't be replicated.

If you're still trying to help, try to look at the [source code](../blob/master/src/contentscript/actions/element.js#L49) and see if there's anything that may cause the action to fail. The 'element' action is basically running querySelectorAll on a loop until it finds one or more elements that are visible on the page. You may make changes and submit a pull request to the upstream later.

**Closed by Frizz925** 2017-06-22 03:52 UTC
